" Encoding
set encoding=utf8
scriptencoding utf-8

" Python3
let g:python3_host_prog = expand('~/anaconda3/envs/neovim/bin/python')

" Plugins
call plug#begin('~/.local/share/neovim/plugged')

    " Aesthetic
    Plug 'lifepillar/vim-solarized8'
    Plug 'shinchu/lightline-gruvbox.vim'
    Plug 'itchyny/lightline.vim'

    " LSP
    Plug 'neovim/nvim-lsp'
    Plug 'haorenW1025/diagnostic-nvim'

    " Autocompletion 
    Plug 'haorenW1025/completion-nvim'

    " Interface
    Plug 'scrooloose/nerdtree'
    Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
    Plug 'junegunn/fzf.vim'

    " Snippets
    Plug 'SirVer/ultisnips'
    Plug 'honza/vim-snippets'
    Plug 'numirias/semshi', {'do': ':UpdateRemotePlugins'}

    " LaTeX
    Plug 'lervag/vimtex'

    " Git
    Plug 'tpope/vim-fugitive'
    Plug 'airblade/vim-gitgutter'

    " Markdown
    Plug 'elzr/vim-json'
    Plug 'plasticboy/vim-markdown'
    Plug 'vim-pandoc/vim-pandoc-syntax'
    Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }}

    " Lua
    Plug 'wsdjeg/vim-lua'

    " Rust 
    Plug 'rust-lang/rust.vim', { 'for': 'rust' }

    " Misc
    Plug 'karadaharu/slimux'
    Plug 'chrisbra/csv.vim'
    Plug 'sbdchd/neoformat'
    Plug 'ledger/vim-ledger'

call plug#end()

let g:vim_home = get(g:, 'vim_home', expand('~/.config/nvim/'))
let config_list = [
    \ 'autocmd.vim',
    \ 'configs.vim',
    \ 'keymapping.vim',
    \ 'plugins.vim',
    \ 'lightline.vim',
    \]
for files in config_list
  for f in glob(g:vim_home.files, 1, 1)
    exec 'source' f
  endfor
endfor

"
" Colorscheme 
" It has to go after the plugins because it is loaded as a plugin
"

colorscheme solarized8
hi clear SpellBad
hi SpellBad cterm=underline
set spell
set spelllang=en,cjk
autocmd FileType plaintex,tex,latex syntax spell toplevel

map <C-c><C-c> :SlimuxREPLSendLine<CR>
vmap <C-c><C-c> :SlimuxREPLSendSelection<CR>
let g:slimux_python_ipython = 1 

